### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by WaleedMortaja** [githubtraining/github-games#3]
this link
https://githubschool.github.io/github-games/
provided in [README.md](https://github.com/githubtraining/github-games/blob/master/README.md)
gives a "404 There isn't a GitHub Pages site here." error.

**Comment by RashVV** [comment]
404 error

**Comment by brianamarie** [comment]
Hello! This is intentional. This link is wrong on purpose, but is later edited to be correct as a part of the Learning Lab course. Since this is a template repository for teaching purposes, the URL in the README.md is serving a non-traditional purpose. I'm going to close this issue, but please let me know if I'm misunderstanding something!

**Comment by WaleedMortaja** [comment]
> Hello! This is intentional. This link is wrong on purpose, but is later edited to be correct as a part of the Learning Lab course. Since this is a template repository for teaching purposes, the URL in the README.md is serving a non-traditional purpose. I'm going to close this issue, but please let me know if I'm misunderstanding something!

You may edit the README.md file to clarify this and put a link for the Learning Lab course if that does not affect the course flow.

**Comment by brianamarie** [comment]
Thanks for the reply, @WaleedMortaja. I misspoke earlier when I said that this is used primarily for Learning Lab. This repository's primary purpose is as a template for our in-person trainings. I will update the description of this repository to include that information.
